### ISSUE TITLE
DES encryption algo with 64 bit keyLength is not supported

### ISSUE THREAD

**Issue by ShubhSingh** [codesqueak/jackson-json-crypto#8]
Hi,

I want to use DES algo but only AES algo with 256 bit keyLength is hardcoded into createSecretKeySpec method of BaseCryptoContext class.

I would suggest to allow changing these values with parameters just like salt and password.

Also in same method iterationCount should also be allowed to change using parameter.

**Comment by ShubhSingh** [comment]
Hi 
I have created the fix for this issue in below PR:
https://github.com/codesqueak/jackson-json-crypto/pull/9

Please approve if you feel it improves the code.

**Comment by shubham-sag** [comment]
@codesqueak This  issue could be closed now as PR is #9 is merged.

**Comment by codesqueak** [comment]
Change now merged.

Thanks for the update

**Comment by ShubhSingh** [comment]
Closing the issue as issue is fixed as mentioned above.
